# Generated by Django 4.1.7 on 2023-03-06 16:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0004_rename_amenities_amenity_alter_amenity_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="amenity",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="amenity",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
